apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: task-manager

type: Opaque

stringData:
  CLOUD_NAME: "fhfrv0gq"
  API_KEY: "742296161159631"
  API_SECRET: "742296161159631"