apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: task-manager

type: Opaque

stringData:
  
  DATABASE_URL: "mongodb://admin:password123@mongodb-service:27017/taskmanager?authSource=admin"
  
  CLOUD_NAME: "fhfrv0gq"
  API_KEY: "742296161159631"
  API_SECRET: "742296161159631"
