apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: task-manager

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual 

  resources:
    requests:
      storage: 500Mi

  